
CREATE OR REPLACE TRIGGER TRG_AUDITORIA
AFTER INSERT OR UPDATE OR DELETE ON USUARIOS
BEGIN
    INSERT INTO AUDITORIA (TABLA, OPERACION, USUARIOBD)
    VALUES ('USUARIOS', ORA_SYSEVENT, USER);
END;
/


CREATE OR REPLACE TRIGGER TRG_AUDITORIA_PACIENTES
AFTER INSERT OR UPDATE OR DELETE ON PACIENTES
BEGIN
    INSERT INTO AUDITORIA (TABLA, OPERACION, USUARIOBD)
    VALUES ('PACIENTES', ORA_SYSEVENT, USER);
END;
/


INSERT INTO USUARIOS (DNI, NOMBRE, TIPO, PASSWORD, ESTADO)
VALUES ('12345678', 'ADMIN PRINCIPAL', 'ADMIN', 'admin@citas.com', 'S');

COMMIT;

